[KoMPoSTInputs]
tIn=0.01;
tOut = 1.0;

InputFile=examples/McDIPPER/initial.dat
OutputFileTag=tau0_0.01_tau_1.0

[KoMPoSTParameters]
EtaOverS = 0.16
EtaOverSTemperatureScale = 0.1

# 0 for free-streaming, 1 for "KoMPoST" EKT evolution ( use 1 for now, implement fs soon)
EVOLUTION_MODE=1

# 0 or 1
ENERGY_PERTURBATIONS=1

# 0 or 1 (must be off in this version)
MOMENTUM_PERTURBATIONS=0

DECOMPOSITION_METHOD=1


[EventInput]
# lattice spacing
afm = 0.12  
deta = 0.12  

# number of grid points
Ns=201;
Neta=201;

# The first grid point to include in the x direction
xSTART=0;
# The last grid point to include in the x direction
xEND=200;

#The first grid point to include in the y direction
ySTART=0;
#The last grid point to include in the y direction
yEND=200;

#The first grid point to include in the eta direction
etaSTART=0;
#The last  grid point to include in the eta direction
etaEND=200;
